server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /api

spring:
  application:
    name: order-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
